# Stage 1: Build Vue app
FROM node:18-alpine AS builder

WORKDIR /app

COPY ./app/package*.json  ./
RUN npm install

COPY ./app .
RUN npm run build

# Stage 2: Serve with Nginx
FROM nginx:alpine


COPY --from=builder /app/dist /usr/share/nginx/html

EXPOSE 80

